# This is a basic workflow to help you get started with Actions

name: Build and Test Source Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: docker build -t my-source-engine .

    - name: Run tests
      run: docker run my-source-engine ./run_tests.sh
      
