# This is a basic workflow to help you get started with Actions

name: Build Source Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install CMake
      uses: lukka/get-cmake@v3

    - name: Configure project
      run: cmake -Bbuild -H. -G "Visual Studio 16 2019"

    - name: Build project
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        ctest -C Release
